# Generated by Django 3.0.1 on 2021-01-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20201217_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.TextField(),
        ),
    ]
