# Generated by Django 3.0.1 on 2021-01-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210121_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
